controller_manager:
  ros__parameters:
    update_rate: 200  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

position_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - joint1
      - joint2
      - joint3
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    gains:
      joint1:
        p: 36.0
        i: 276.0
        d: 1.95
        i_clamp: 15.0
        antiwindup: true
      joint2:
        p: 36.0
        i: 570.0
        d: 0.95
        i_clamp: 15.0
        antiwindup: true
      joint3:
        p: 36.0    
        i: 276.0
        d: 1.95
        i_clamp: 15.0
        antiwindup: true

effort_controller:
  ros__parameters:
    type: effort_controllers/JointGroupEffortController
    joints:
      - joint1
      - joint2
      - joint3
    interface_name: effort





